version: '3.3'
services:
  phpapp:
    image: supercali
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./app:/var/www/html
    depends_on:
      - mysql
    networks:
      - supercali

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    networks:
      - supercali
    ports:
      - '3306'
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:

networks:
  supercali:
    driver: bridge